SentimentAnalysis/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("main.urls")),
]

main/urls.py
from django.urls import path
from . import views

app_name = "main"

urlpatterns = [
    path("", views.homepage, name="homepage"),
    path("result/", views.result, name="result")
]

main/models.py
from django.db import models

# Create your models here.

SentimentAnalysis/main/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib import messages
import tweepy 
from textblob import TextBlob 
import pandas as pd
import numpy as np
import urllib.request
import re
import os

# Home and Intro page
def homepage(request):
    return render(request, "main/home.html", {})

# Returns the authenticated Tweepy api
def get_tweepy():
    try:
        consumer_key = "aCl9MzDUdij6MQC4wE6VmG4x3"
        consumer_secret = "T7l1vWsRhSNgwj0FYNIEBsGYoqfCOAH0ZGFlhK1bL57LHAFeyQ"
        access_token = "1422123417533403137-KhXMWgcGgK1KQ3CJShSGgKrS2wGUgF"
        access_token_secret = "t3diDW8IqKe7PSjR9K0K9HQXqZ8r1AmqwL5ysYqu7W7kp"

        auth = tweepy.OAuthHandler(consumer_key, consumer_secret)
        auth.set_access_token(access_token, access_token_secret)

        api = tweepy.API(auth, wait_on_rate_limit = True)

        return api
    
    except Exception as e:
        print(e)

# returns the cleaned tweet text
def cleanTxt(text):
    #removes @mentions
    text = re.sub(r'@[A-Za-z0-9]+', '', text)
    #removes hashtags
    text = re.sub(r'#', '', text)
    #removes RT
    text = re.sub(r'RT[\s]+', '', text)
    #removes hyper link
    text = re.sub(r'https?:\/\/\S+', '', text)

    return text

# Returns polarity of the sentiments
def getPolarity(text):
    return TextBlob(text).sentiment.polarity


# Analyzes the polarity of the sentiments
def getAnalysis(score):
    if score < 0:
        return 'Negative'
    
    elif score == 0:
        return "Neutral"

    else:
        return 'Positive'

# result page shows the analyzation of the data
def result(request):
    if request.method == "POST":
        try:
            # Gets the text from the input bar
            text = request.POST.get('text')

            api = get_tweepy()

            # Searches for 500 tweets that contain the text
            cursor = api.search(text, count=1200, lang="en")

            # Adds Tweets found to a set to remove duplicate ones
            Tweets = set()
            for t in cursor:
                Tweets.add(t.text)

            # Creates a dataframe with a column for the tweets found
            df = pd.DataFrame(data=[tweet for tweet in Tweets], columns=['Tweets'])
            pd.set_option('display.max_colwidth', None)

            #  Gets the links of the tweets that exist in the Tweets set only
            links = []
            for i in Tweets:
                for s in cursor:
                    if s.text == i:
                        links.append("https://twitter.com/twitter/statuses/" + str(s.id))
                        break
                    
            # Creates a new column for links
            df["Links"] = links

            # Displays error message if the dataframe is empty
            if df.empty:
                messages.error(request, "Invalid Input")
                return render(request, 
                    "main/home.html", 
                    {})
            
            # Applies tweet text cleaning
            df['Tweets'] = df['Tweets'].apply(cleanTxt) 
            # Applies getPolarity to the Tweets column and creates a Polarity column with the resuts
            df['Polarity'] = df['Tweets'].apply(getPolarity)
            # Applies getAnalysis to the Polarity column and creates Analysis column with the results
            df['Analysis'] = df['Polarity'].apply(getAnalysis)

            # Add the links to a new column in the dataframe
            df["Links"] = links
            
            # List for tweet objects
            objects = []

            # Counting how many tweets are negative, positive or neutral
            # Creating Tweet object and adding it to objects list
            chart={"Negative":0, "Positive":0, "Neutral":0}
            for i in range(0,df.shape[0]):
                if(df['Analysis'][i] == 'Negative'):
                    chart['Negative'] +=1
 
                    TweetObject = Tweet(polarity="Negative", link=df["Links"][i], tweet= df["Tweets"][i])
                    objects.append(TweetObject)
    
                elif(df['Analysis'][i] == 'Positive'):
                    chart['Positive'] +=1
                    
                    TweetObject = Tweet(polarity="Positive", link=df["Links"][i], tweet= df["Tweets"][i])
                    objects.append(TweetObject)
    
                elif(df['Analysis'][i] == 'Neutral'):
                    chart['Neutral'] +=1
                    
                    TweetObject = Tweet(polarity="Neutral", link=df["Links"][i], tweet= df["Tweets"][i])
                    objects.append(TweetObject)
            
            sumOfTweets = chart["Negative"] + chart["Positive"] + chart["Neutral"]
            
            # Percentage of each result
            Negative_Percent = str(int((chart["Negative"] /  sumOfTweets) * 100)) + "%"
            Positive_Percent = str(int((chart["Positive"] /  sumOfTweets) * 100)) + "%"
            Neutral_Percent = str(int((chart["Neutral"] /  sumOfTweets) * 100)) + "%"

            return render(request, 
                    "main/result.html", 
                    {"analysis":chart, "negative":Negative_Percent, 
                    "posi":Positive_Percent, "neu":Neutral_Percent, "Text":text, "Tweets":objects})

        except Exception as e:
            print(e)

    return render(request, 
                  "main/home.html", 
                  {})
                  
class Tweet:
     def __init__(self, polarity, link, tweet):
        self.tweet = tweet
        self.link = link
        self.polarity = polarity

main/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib import messages
import tweepy 
from textblob import TextBlob 
import pandas as pd
import numpy as np
import urllib.request
import re
import os

# Home and Intro page
def homepage(request):
    return render(request, "main/home.html", {})

# Returns the authenticated Tweepy api
def get_tweepy():
    try:
        consumer_key = os.environ.get('C_K')
        consumer_secret = os.environ.get('C_S')
        access_token = os.environ.get('A_T')
        access_token_secret = os.environ.get('A_T_S')

        auth = tweepy.OAuthHandler(consumer_key, consumer_secret)
        auth.set_access_token(access_token, access_token_secret)

        api = tweepy.API(auth, wait_on_rate_limit = True)

        return api
    
    except Exception as e:
        print(e)

# returns the cleaned tweet text
def cleanTxt(text):
    #removes @mentions
    text = re.sub(r'@[A-Za-z0-9]+', '', text)
    #removes hashtags
    text = re.sub(r'#', '', text)
    #removes RT
    text = re.sub(r'RT[\s]+', '', text)
    #removes hyper link
    text = re.sub(r'https?:\/\/\S+', '', text)

    return text

# Returns polarity of the sentiments
def getPolarity(text):
    return TextBlob(text).sentiment.polarity


# Analyzes the polarity of the sentiments
def getAnalysis(score):
    if score < 0:
        return 'Negative'
    
    elif score == 0:
        return "Neutral"

    else:
        return 'Positive'

# result page shows the analyzation of the data
def result(request):
    if request.method == "POST":
        try:
            # Gets the text from the input bar
            text = request.POST.get('text')

            api = get_tweepy()

            # Searches for 500 tweets that contain the text
            cursor = api.search(text, count=1200, lang="en")

            # Adds Tweets found to a set to remove duplicate ones
            Tweets = set()
            for t in cursor:
                Tweets.add(t.text)

            # Creates a dataframe with a column for the tweets found
            df = pd.DataFrame(data=[tweet for tweet in Tweets], columns=['Tweets'])
            pd.set_option('display.max_colwidth', None)

            #  Gets the links of the tweets that exist in the Tweets set only
            links = []
            for i in Tweets:
                for s in cursor:
                    if s.text == i:
                        links.append("https://twitter.com/twitter/statuses/" + str(s.id))
                        break
                    
            # Creates a new column for links
            df["Links"] = links

            # Displays error message if the dataframe is empty
            if df.empty:
                messages.error(request, "Invalid Input")
                return render(request, 
                    "main/home.html", 
                    {})
            
            # Applies tweet text cleaning
            df['Tweets'] = df['Tweets'].apply(cleanTxt) 
            # Applies getPolarity to the Tweets column and creates a Polarity column with the resuts
            df['Polarity'] = df['Tweets'].apply(getPolarity)
            # Applies getAnalysis to the Polarity column and creates Analysis column with the results
            df['Analysis'] = df['Polarity'].apply(getAnalysis)

            # Add the links to a new column in the dataframe
            df["Links"] = links
            
            # List for tweet objects
            objects = []

            # Counting how many tweets are negative, positive or neutral
            # Creating Tweet object and adding it to objects list
            chart={"Negative":0, "Positive":0, "Neutral":0}
            for i in range(0,df.shape[0]):
                if(df['Analysis'][i] == 'Negative'):
                    chart['Negative'] +=1
 
                    TweetObject = Tweet(polarity="Negative", link=df["Links"][i], tweet= df["Tweets"][i])
                    objects.append(TweetObject)
    
                elif(df['Analysis'][i] == 'Positive'):
                    chart['Positive'] +=1
                    
                    TweetObject = Tweet(polarity="Positive", link=df["Links"][i], tweet= df["Tweets"][i])
                    objects.append(TweetObject)
    
                elif(df['Analysis'][i] == 'Neutral'):
                    chart['Neutral'] +=1
                    
                    TweetObject = Tweet(polarity="Neutral", link=df["Links"][i], tweet= df["Tweets"][i])
                    objects.append(TweetObject)
            
            sumOfTweets = chart["Negative"] + chart["Positive"] + chart["Neutral"]
            
            # Percentage of each result
            Negative_Percent = str(int((chart["Negative"] /  sumOfTweets) * 100)) + "%"
            Positive_Percent = str(int((chart["Positive"] /  sumOfTweets) * 100)) + "%"
            Neutral_Percent = str(int((chart["Neutral"] /  sumOfTweets) * 100)) + "%"

            return render(request, 
                    "main/result.html", 
                    {"analysis":chart, "negative":Negative_Percent, 
                    "posi":Positive_Percent, "neu":Neutral_Percent, "Text":text, "Tweets":objects})

        except Exception as e:
            print(e)

    return render(request, 
                  "main/home.html", 
                  {})

# Tweet class for storing tweet information         
class Tweet:
     def __init__(self, polarity, link, tweet):
        self.tweet = tweet
        self.link = link
        self.polarity = polarity

main/templates/main/header.html
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <!--bootstrap-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
    
    <script src="https://cdn.jsdelivr.net/npm/chart.js@3.5.0/dist/chart.min.js"></script>

    <!--icons-->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
</head>

<body style="text-align:center;" class="bg-info bg-opacity-25"> 

    {% if messages %}
        {% for m in messages%}
            <div class="alert alert-danger alert-dismissible fade show" role="alert">
                <strong>{{m}}</strong>
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        {% endfor %}
    {% endif %}

    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj" crossorigin="anonymous"></script>
</body>      

main/templates/main/home.html
{% extends 'main/header.html' %}

{% block content %}
    
    <h1 class="display-4">Tweepy Sentiments Analyzer</h1>

    <h1 class="display-3" style="font-size: 23px;">Enter what's in your mind to see how people feel about it</h1>

    <p>
    <form method="post" action="{% url 'main:result'%}">
    {%csrf_token%}
        <div class="input-group flex-nowrap ">
            <span class="input-group-text bg-info" id="addon-wrapping"><i class="bi bi-twitter"></i></span>
            <input type="text" class="form-control" aria-label="Username" aria-describedby="addon-wrapping" name="text">
        </div>
    </form>
    </p>

    

{% endblock %}

main/templates/main/result.html
{% extends 'main/header.html' %}

{% block content %}

<h1 class="display-5">"{{Text}}"</h1>

<div class="row d-flex justify-content-center">
    <div class="card text-center bg-info bg-opacity-50" style="width: 18rem;">
        <div class="card-body">
            <p>
                <svg xmlns="http://www.w3.org/2000/svg" width="57" height="57" fill="#000080" class="bi bi-emoji-frown-fill" viewBox="0 0 16 16">
                    <path d="M8 16A8 8 0 1 0 8 0a8 8 0 0 0 0 16zM7 6.5C7 7.328 6.552 8 6 8s-1-.672-1-1.5S5.448 5 6 5s1 .672 1 1.5zm-2.715 5.933a.5.5 0 0 1-.183-.683A4.498 4.498 0 0 1 8 9.5a4.5 4.5 0 0 1 3.898 2.25.5.5 0 0 1-.866.5A3.498 3.498 0 0 0 8 10.5a3.498 3.498 0 0 0-3.032 1.75.5.5 0 0 1-.683.183zM10 8c-.552 0-1-.672-1-1.5S9.448 5 10 5s1 .672 1 1.5S10.552 8 10 8z"/>
                </svg>
                {{negative}}
            </p>    
            <button class="btn btn-primary bg-info" type="button" data-bs-toggle="collapse" data-bs-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
                Show Tweets
            </button>
            <p>
                <div class="collapse" id="collapseExample">
                    <div class="card card-body">
                        <ul>
                            {% for o in Tweets%}
                                    {% if o.polarity == "Negative" %}
                                        <p><li><a href="{{o.link}}">{{o.tweet}}</a></li></p>
                                    {% endif %}
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </p>
        </div>
    </div>
    <div class="card text-center bg-info bg-opacity-50" style="width: 18rem;">
        <div class="card-body">
            <p>
                <svg xmlns="http://www.w3.org/2000/svg" width="57" height="57" fill='#d4c9b9' class="bi bi-emoji-neutral-fill" viewBox="0 0 16 16">
                    <path d="M8 16A8 8 0 1 0 8 0a8 8 0 0 0 0 16zM7 6.5C7 7.328 6.552 8 6 8s-1-.672-1-1.5S5.448 5 6 5s1 .672 1 1.5zm-3 4a.5.5 0 0 1 .5-.5h7a.5.5 0 0 1 0 1h-7a.5.5 0 0 1-.5-.5zM10 8c-.552 0-1-.672-1-1.5S9.448 5 10 5s1 .672 1 1.5S10.552 8 10 8z"/>
                </svg>
                {{neu}}
            </p>    
            <button class="btn btn-primary bg-info" type="button" data-bs-toggle="collapse" data-bs-target="#collapseExample2" aria-expanded="false" aria-controls="collapseExample">
                Show Tweets
            </button>
            <p>
                <div class="collapse" id="collapseExample2">
                    <div class="card card-body">
                        <ul>
                            {% for o in Tweets%}
                                    {% if o.polarity == "Neutral" %}
                                        <p><li><a href="{{o.link}}">{{o.tweet}}</a></li></p>
                                    {% endif %}
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </p>
        </div>
    </div>
    <div class="card text-center bg-info bg-opacity-50" style="width: 18rem;">
        <div class="card-body">
            <p>
                <svg xmlns="http://www.w3.org/2000/svg" width="57" height="57" fill="rgb(255, 205, 86)" class="bi bi-emoji-smile-fill " viewBox="0 0 16 16">
                    <path d="M8 16A8 8 0 1 0 8 0a8 8 0 0 0 0 16zM7 6.5C7 7.328 6.552 8 6 8s-1-.672-1-1.5S5.448 5 6 5s1 .672 1 1.5zM4.285 9.567a.5.5 0 0 1 .683.183A3.498 3.498 0 0 0 8 11.5a3.498 3.498 0 0 0 3.032-1.75.5.5 0 1 1 .866.5A4.498 4.498 0 0 1 8 12.5a4.498 4.498 0 0 1-3.898-2.25.5.5 0 0 1 .183-.683zM10 8c-.552 0-1-.672-1-1.5S9.448 5 10 5s1 .672 1 1.5S10.552 8 10 8z"/>
                </svg>
                {{posi}}
            </p>    
            <button class="btn btn-primary bg-info" type="button" data-bs-toggle="collapse" data-bs-target="#collapseExample3" aria-expanded="false" aria-controls="collapseExample">
                Show Tweets
            </button>
            <p>
                <div class="collapse" id="collapseExample3">
                    <div class="card card-body">
                        <ul>
                            {% for o in Tweets%}
                                    {% if o.polarity == "Positive" %}
                                       <p><li><a href="{{o.link}}">{{o.tweet}}</a></li></p>
                                    {% endif %}
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </p>
        </div>
    </div>
</div>
<div class="row"></div>
<div class="row d-flex justify-content-around">
    <div class="col-md-8 bg-info bg-opacity-50" style="width:500px; height:500px;">
        <canvas id="myChart"></canvas>
        <script>
        var ctx = document.getElementById('myChart').getContext('2d');
        var myChart = new Chart(ctx, {
            type: 'pie',
            data: {  
                labels: [
                        'Negative',
                        'Neutral',
                        'Positive'
                        ],
                datasets: [{
                            label: 'My First Dataset',
                            data: [{{analysis.Negative}}, {{analysis.Neutral}}, {{analysis.Positive}}],
                            backgroundColor: [
                                                '#000080',
                                                '#d4c9b9',
                                                'rgb(255, 205, 86)'
                                                ],
                            hoverOffset: 4
                        }]
            },
            legend: {
                display: false  
            }
        });
        </script>
    </div>
</div>
    


{% endblock %}